/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedPontoRouteImport } from './routes/_authenticated/ponto'
import { Route as AuthenticatedInvitesRouteImport } from './routes/_authenticated/invites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSocialContentRouteImport } from './routes/_authenticated/social.content'
import { Route as AuthenticatedAreaSlugIndexRouteImport } from './routes/_authenticated/area.$slug.index'
import { Route as AuthenticatedAreaSlugProjectIdRouteImport } from './routes/_authenticated/area.$slug.project.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPontoRoute = AuthenticatedPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitesRoute = AuthenticatedInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialContentRoute =
  AuthenticatedSocialContentRouteImport.update({
    id: '/social/content',
    path: '/social/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreaSlugIndexRoute =
  AuthenticatedAreaSlugIndexRouteImport.update({
    id: '/area/$slug/',
    path: '/area/$slug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreaSlugProjectIdRoute =
  AuthenticatedAreaSlugProjectIdRouteImport.update({
    id: '/area/$slug/project/$id',
    path: '/area/$slug/project/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/social/content': typeof AuthenticatedSocialContentRoute
  '/area/$slug/': typeof AuthenticatedAreaSlugIndexRoute
  '/area/$slug/project/$id': typeof AuthenticatedAreaSlugProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invites': typeof AuthenticatedInvitesRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/social/content': typeof AuthenticatedSocialContentRoute
  '/area/$slug': typeof AuthenticatedAreaSlugIndexRoute
  '/area/$slug/project/$id': typeof AuthenticatedAreaSlugProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invites': typeof AuthenticatedInvitesRoute
  '/_authenticated/ponto': typeof AuthenticatedPontoRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/social/content': typeof AuthenticatedSocialContentRoute
  '/_authenticated/area/$slug/': typeof AuthenticatedAreaSlugIndexRoute
  '/_authenticated/area/$slug/project/$id': typeof AuthenticatedAreaSlugProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/invites'
    | '/ponto'
    | '/setup'
    | '/social/content'
    | '/area/$slug/'
    | '/area/$slug/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/invites'
    | '/ponto'
    | '/setup'
    | '/social/content'
    | '/area/$slug'
    | '/area/$slug/project/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/invites'
    | '/_authenticated/ponto'
    | '/_authenticated/setup'
    | '/_authenticated/social/content'
    | '/_authenticated/area/$slug/'
    | '/_authenticated/area/$slug/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ponto': {
      id: '/_authenticated/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof AuthenticatedPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invites': {
      id: '/_authenticated/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AuthenticatedInvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/content': {
      id: '/_authenticated/social/content'
      path: '/social/content'
      fullPath: '/social/content'
      preLoaderRoute: typeof AuthenticatedSocialContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area/$slug/': {
      id: '/_authenticated/area/$slug/'
      path: '/area/$slug'
      fullPath: '/area/$slug/'
      preLoaderRoute: typeof AuthenticatedAreaSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area/$slug/project/$id': {
      id: '/_authenticated/area/$slug/project/$id'
      path: '/area/$slug/project/$id'
      fullPath: '/area/$slug/project/$id'
      preLoaderRoute: typeof AuthenticatedAreaSlugProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvitesRoute: typeof AuthenticatedInvitesRoute
  AuthenticatedPontoRoute: typeof AuthenticatedPontoRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSocialContentRoute: typeof AuthenticatedSocialContentRoute
  AuthenticatedAreaSlugIndexRoute: typeof AuthenticatedAreaSlugIndexRoute
  AuthenticatedAreaSlugProjectIdRoute: typeof AuthenticatedAreaSlugProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvitesRoute: AuthenticatedInvitesRoute,
  AuthenticatedPontoRoute: AuthenticatedPontoRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSocialContentRoute: AuthenticatedSocialContentRoute,
  AuthenticatedAreaSlugIndexRoute: AuthenticatedAreaSlugIndexRoute,
  AuthenticatedAreaSlugProjectIdRoute: AuthenticatedAreaSlugProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
