/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSocialContentRouteImport } from './routes/_authenticated/social.content'
import { Route as AuthenticatedAreaSlugRouteImport } from './routes/_authenticated/area.$slug'
import { Route as AuthenticatedAreaSlugProjectIdRouteImport } from './routes/_authenticated/area.$slug.project.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialContentRoute =
  AuthenticatedSocialContentRouteImport.update({
    id: '/social/content',
    path: '/social/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreaSlugRoute = AuthenticatedAreaSlugRouteImport.update({
  id: '/area/$slug',
  path: '/area/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreaSlugProjectIdRoute =
  AuthenticatedAreaSlugProjectIdRouteImport.update({
    id: '/project/$id',
    path: '/project/$id',
    getParentRoute: () => AuthenticatedAreaSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/area/$slug': typeof AuthenticatedAreaSlugRouteWithChildren
  '/social/content': typeof AuthenticatedSocialContentRoute
  '/area/$slug/project/$id': typeof AuthenticatedAreaSlugProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/area/$slug': typeof AuthenticatedAreaSlugRouteWithChildren
  '/social/content': typeof AuthenticatedSocialContentRoute
  '/area/$slug/project/$id': typeof AuthenticatedAreaSlugProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/area/$slug': typeof AuthenticatedAreaSlugRouteWithChildren
  '/_authenticated/social/content': typeof AuthenticatedSocialContentRoute
  '/_authenticated/area/$slug/project/$id': typeof AuthenticatedAreaSlugProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/area/$slug'
    | '/social/content'
    | '/area/$slug/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/area/$slug'
    | '/social/content'
    | '/area/$slug/project/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/area/$slug'
    | '/_authenticated/social/content'
    | '/_authenticated/area/$slug/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/content': {
      id: '/_authenticated/social/content'
      path: '/social/content'
      fullPath: '/social/content'
      preLoaderRoute: typeof AuthenticatedSocialContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area/$slug': {
      id: '/_authenticated/area/$slug'
      path: '/area/$slug'
      fullPath: '/area/$slug'
      preLoaderRoute: typeof AuthenticatedAreaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area/$slug/project/$id': {
      id: '/_authenticated/area/$slug/project/$id'
      path: '/project/$id'
      fullPath: '/area/$slug/project/$id'
      preLoaderRoute: typeof AuthenticatedAreaSlugProjectIdRouteImport
      parentRoute: typeof AuthenticatedAreaSlugRoute
    }
  }
}

interface AuthenticatedAreaSlugRouteChildren {
  AuthenticatedAreaSlugProjectIdRoute: typeof AuthenticatedAreaSlugProjectIdRoute
}

const AuthenticatedAreaSlugRouteChildren: AuthenticatedAreaSlugRouteChildren = {
  AuthenticatedAreaSlugProjectIdRoute: AuthenticatedAreaSlugProjectIdRoute,
}

const AuthenticatedAreaSlugRouteWithChildren =
  AuthenticatedAreaSlugRoute._addFileChildren(
    AuthenticatedAreaSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAreaSlugRoute: typeof AuthenticatedAreaSlugRouteWithChildren
  AuthenticatedSocialContentRoute: typeof AuthenticatedSocialContentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAreaSlugRoute: AuthenticatedAreaSlugRouteWithChildren,
  AuthenticatedSocialContentRoute: AuthenticatedSocialContentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
